package com.company;

import java.util.HashMap;
import java.util.Map;

public class Task {
    static String str= "IMPEDFCJYEIPDTUOSWMYSMIAQYDEONTZTWRNGZFXKYBTLFZFJAUJWOYSECCYUJQJXHKNLEGKDMXLOEFVIFGULESWVMRXRUFZGRTUEUWELUFBLTAJAYSKTZNPEJZZRLKATPQBZHLFFHXLDKWOYTIXSGPCTHFOMOTCKSBOFIJBOBUGJYOIQLBAKKRWVHXSSXRZTQRMKAQSXODALBXZCKYZXATCXHBHKMTWGRRHEPQKNGXLIXHYTTAZSWVCZZUBEOXMUXAHEVBILLJRRVSGRIEUIULKBIPJHGXIKWYGYXZTGEFYDGYVKPRRSFJJRLDDQCUEDFFPEEHOTMWAOEMLXWXVIHIJLRCVIQXGZTXDBNXQGZSYNSIYQBPLNTXDKIJVTJOGKKKAYTVUHMVVTWKOCHETOAZBEPNKQQKCBGLJSOQHRRTQILQKFYHQLSACFNMZTCGLGAZIRINEJRLMHPRDGOTNYIOJDNDFYCIGIACALITODHZHJJXJNZWEUDMFWYPNCDYFOKGNTWPONTQLMMXFDNWZVYARYUEBJIPHGCRMFWTMPTXVERDRGXPMOVLWEYJTXWEAPJXKHKCMSWWIPMQFWSVKIWLUVAKKUUQWAOBDDLRGOWHGQDHSCNUPRJOPRMEGLISBUKQWKTSJCNBVDUQZIHUHPYOAZMKSHKIIWMXSZVLCPCJDRVMSJIDXNLNNVLRMNNKXDYSOKKXMWNRXVVOGKYNTHFAUNKSDZUPKUXPUVKNVQCZJRXSIZQYWHDLOXLVLVENIBQPCMDFCGTGZMQMORQLRAKVMXMNLIGOSYVAIAORAIDUPFHHTRFCPPBYQWQCKJYQMKAETCGHBCEJSSFVXVSIPGFMEOPXAXPYKCWZZGMFWIERBIODKFEKLXOXVQDFQOOORODUSNRCVUWLHOMEETODKDUCKVIQUXYYUFPZALYMKPYNBYTWFHVKGAIEZWSXRUOEONGNEMLDWMNJGEVODASJIJKOJWGLKJKEATXBNODCK";

    public static void main(String[] args) {
        char chars[] = str.toCharArray();
        HashMap<Character,Integer> map = new HashMap<>();
        for(Character c : str.toCharArray()){
            if(map.containsKey(c)){
                map.put(c,map.get(c)+1);
                continue;
            }
            map.put(c,1);
        }

        map.entrySet().stream()
                .sorted(Map.Entry.<Character, Integer>comparingByValue().reversed())
                .forEach(System.out::println);

    }
}
